# Generated by Django 4.1.7 on 2023-03-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('title_brand', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careng', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mark', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mod', models.CharField(max_length=250)),
                ('carmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmark', verbose_name='carmark')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('article', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title_goods', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, max_length=3500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carengine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carengine', verbose_name='carengine')),
                ('carmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmark', verbose_name='carmark')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmodel', verbose_name='carmodel')),
                ('goodsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.goods', verbose_name='ggggggggooodsi')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_dictionary', models.CharField(max_length=120, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='category_dictionaries', to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='dictionaries',
            field=models.ManyToManyField(blank=True, related_name='category_dictionaries', to='products.dictionarycategory'),
        ),
        migrations.AddField(
            model_name='carengine',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmodel', verbose_name='carmodel'),
        ),
        migrations.CreateModel(
            name='AllowedCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carengine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carengine')),
                ('carmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmark')),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.carmodel')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
